services:
  backend:
    build: .
    container_name: resume-backend
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/resume-database
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: letmein
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    image: resume-backend:latest
    networks:
      - resume-network
    ports:
      - "8443:8443"
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt/live/fynn-koch.de/keystore.p12:/etc/letsencrypt/live/fynn-koch.de/keystore.p12:ro

  database:
    container_name: resume-database
    environment:
      POSTGRES_DB: resume-database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: letmein
    image: postgres:16.3
    networks:
      - resume-network
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  resume-network:
    external: true
