server:
  port: 8443
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/fynn-koch.de/keystore.p12
    key-store-password: ''
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/resume-database
    username: admin
    password: letmein
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-version: 1
    locations: classpath:db
    clean-on-validation-error: false
    connect-retries: 5
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
springdoc:
  api-docs:
    path: '/docs'
  swagger-ui:
    path: '/docs/ui'
    operations-sorter: method

basic-auth:
  username: admin
  password: admin